import type { Metadata } from "next";
import { Sora } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { Footer, Navbar } from "@/components";
import { ChakraProvider } from "@chakra-ui/react";
import "./globals.css";

const inter = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SMG website",
  description: "Generated by create next app",
};

const whatsappNumber = "+234013300401";
const message = "Hi, I want to make enquiries";
const encodedMessage = encodeURIComponent(message);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <NextTopLoader />
          <Navbar />
          {children}
          <Footer />
          <a
            href={`https://wa.me/${whatsappNumber}/?text=${encodedMessage}`}
            target="_blank"
            className="fixed bottom-5 right-5 z-50 bg-white rounded-md p-3"
          >
            <div>
              <img
                src="/icons/whatsapp-icon.svg"
                alt="whatsapp"
                width={32}
                height={32}
              />
            </div>
          </a>
        </ChakraProvider>
      </body>
    </html>
  );
}
